### ISSUE TITLE
Pad paragraph text

### ISSUE THREAD

**Issue by GiacomoLaw** [GiacomoLaw/british-airways-virtual#7]

**Comment by ermassey** [comment]
I would also say do it on the video; up to you

**Comment by GiacomoLaw** [comment]
Video goes edge to edge on screen. That's the way it is meant to be. If someone wants to change that, they can do it whilst editing the CSS 😄

**Comment by GiacomoLaw** [comment]
Fixed: https://github.com/GiacomoLaw/va-website-template/commit/d295188b8a43bbf4855075dd4d5ea53d3745d24e
